@echo off
C:\msys64\mingw64\bin\g++.exe -c -O2 -DUNICODE -D_UNICODE -DWIN32 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_PRINTSUPPORT_LIB -DQT_CORE_LIB -I. -I"C:/msys64/mingw64/include/qt6" -I"C:/msys64/mingw64/include/qt6/QtWidgets" -I"C:/msys64/mingw64/include/qt6/QtGui" -I"C:/msys64/mingw64/include/qt6/QtNetwork" -I"C:/msys64/mingw64/include/qt6/QtPrintSupport" -I"C:/msys64/mingw64/include/qt6/QtCore" qcustomplot.cpp -o qcustomplot.o
C:\msys64\mingw64\bin\g++.exe -c -O2 -DUNICODE -D_UNICODE -DWIN32 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_PRINTSUPPORT_LIB -DQT_CORE_LIB -I. -I"C:/msys64/mingw64/include/qt6" -I"C:/msys64/mingw64/include/qt6/QtWidgets" -I"C:/msys64/mingw64/include/qt6/QtGui" -I"C:/msys64/mingw64/include/qt6/QtNetwork" -I"C:/msys64/mingw64/include/qt6/QtPrintSupport" -I"C:/msys64/mingw64/include/qt6/QtCore" main.cpp -o main.o
C:\msys64\mingw64\bin\g++.exe -c -O2 -DUNICODE -D_UNICODE -DWIN32 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_PRINTSUPPORT_LIB -DQT_CORE_LIB -I. -I"C:/msys64/mingw64/include/qt6" -I"C:/msys64/mingw64/include/qt6/QtWidgets" -I"C:/msys64/mingw64/include/qt6/QtGui" -I"C:/msys64/mingw64/include/qt6/QtNetwork" -I"C:/msys64/mingw64/include/qt6/QtPrintSupport" -I"C:/msys64/mingw64/include/qt6/QtCore" mainwindow.cpp -o mainwindow.o
C:\msys64\mingw64\bin\g++.exe -c -O2 -DUNICODE -D_UNICODE -DWIN32 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_PRINTSUPPORT_LIB -DQT_CORE_LIB -I. -I"C:/msys64/mingw64/include/qt6" -I"C:/msys64/mingw64/include/qt6/QtWidgets" -I"C:/msys64/mingw64/include/qt6/QtGui" -I"C:/msys64/mingw64/include/qt6/QtNetwork" -I"C:/msys64/mingw64/include/qt6/QtPrintSupport" -I"C:/msys64/mingw64/include/qt6/QtCore" authform.cpp -o authform.o
C:\msys64\mingw64\bin\g++.exe -c -O2 -DUNICODE -D_UNICODE -DWIN32 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_PRINTSUPPORT_LIB -DQT_CORE_LIB -I. -I"C:/msys64/mingw64/include/qt6" -I"C:/msys64/mingw64/include/qt6/QtWidgets" -I"C:/msys64/mingw64/include/qt6/QtGui" -I"C:/msys64/mingw64/include/qt6/QtNetwork" -I"C:/msys64/mingw64/include/qt6/QtPrintSupport" -I"C:/msys64/mingw64/include/qt6/QtCore" titleform.cpp -o titleform.o
C:\msys64\mingw64\bin\g++.exe -c -O2 -DUNICODE -D_UNICODE -DWIN32 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_PRINTSUPPORT_LIB -DQT_CORE_LIB -I. -I"C:/msys64/mingw64/include/qt6" -I"C:/msys64/mingw64/include/qt6/QtWidgets" -I"C:/msys64/mingw64/include/qt6/QtGui" -I"C:/msys64/mingw64/include/qt6/QtNetwork" -I"C:/msys64/mingw64/include/qt6/QtPrintSupport" -I"C:/msys64/mingw64/include/qt6/QtCore" taskform.cpp -o taskform.o
C:\msys64\mingw64\bin\g++.exe -c -O2 -DUNICODE -D_UNICODE -DWIN32 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_PRINTSUPPORT_LIB -DQT_CORE_LIB -I. -I"C:/msys64/mingw64/include/qt6" -I"C:/msys64/mingw64/include/qt6/QtWidgets" -I"C:/msys64/mingw64/include/qt6/QtGui" -I"C:/msys64/mingw64/include/qt6/QtNetwork" -I"C:/msys64/mingw64/include/qt6/QtPrintSupport" -I"C:/msys64/mingw64/include/qt6/QtCore" dashboardform.cpp -o dashboardform.o
C:\msys64\mingw64\bin\g++.exe -c -O2 -DUNICODE -D_UNICODE -DWIN32 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_PRINTSUPPORT_LIB -DQT_CORE_LIB -I. -I"C:/msys64/mingw64/include/qt6" -I"C:/msys64/mingw64/include/qt6/QtWidgets" -I"C:/msys64/mingw64/include/qt6/QtGui" -I"C:/msys64/mingw64/include/qt6/QtNetwork" -I"C:/msys64/mingw64/include/qt6/QtPrintSupport" -I"C:/msys64/mingw64/include/qt6/QtCore" socketmanager.cpp -o socketmanager.o
C:\msys64\mingw64\bin\g++.exe -Wl,-s -Wl,-subsystem,windows -mthreads -o Client.exe main.o mainwindow.o authform.o titleform.o taskform.o dashboardform.o socketmanager.o qcustomplot.o C:/msys64/mingw64/lib/libQt6PrintSupport.dll.a C:/msys64/mingw64/lib/libQt6Widgets.dll.a C:/msys64/mingw64/lib/libQt6Gui.dll.a C:/msys64/mingw64/lib/libQt6Network.dll.a C:/msys64/mingw64/lib/libQt6Core.dll.a -lmingw32 C:/msys64/mingw64/lib/libQt6EntryPoint.a -lshell32
echo DONE!
pause
