var dir_1a445cb237d74f7a5f8d11ec3b0585cc =
[
    [ "build", "dir_91445b934ec3b4b9c264c209426228af.html", "dir_91445b934ec3b4b9c264c209426228af" ],
    [ "Server", "dir_3ed6d5539aca52d7d36d47d992bc57d4.html", "dir_3ed6d5539aca52d7d36d47d992bc57d4" ],
    [ "calculator.cpp", "calculator_8cpp.html", null ],
    [ "calculator.h", "calculator_8h.html", "calculator_8h" ],
    [ "database.cpp", "database_8cpp.html", null ],
    [ "database.h", "database_8h.html", "database_8h" ],
    [ "db_handler.cpp", "db__handler_8cpp.html", null ],
    [ "db_handler.h", "db__handler_8h.html", "db__handler_8h" ],
    [ "dbmanager.cpp", "dbmanager_8cpp.html", null ],
    [ "dbmanager.h", "dbmanager_8h.html", "dbmanager_8h" ],
    [ "functionsforserver.cpp", "functionsforserver_8cpp.html", "functionsforserver_8cpp" ],
    [ "functionsforserver.h", "functionsforserver_8h.html", "functionsforserver_8h" ],
    [ "logger.h", "logger_8h.html", "logger_8h" ],
    [ "main.cpp", "_server_2main_8cpp.html", "_server_2main_8cpp" ],
    [ "myserver.cpp", "myserver_8cpp.html", null ],
    [ "myserver.h", "myserver_8h.html", "myserver_8h" ],
    [ "mytcpserver.cpp", "mytcpserver_8cpp.html", "mytcpserver_8cpp" ],
    [ "mytcpserver.h", "mytcpserver_8h.html", "mytcpserver_8h" ],
    [ "protocol.cpp", "protocol_8cpp.html", "protocol_8cpp" ],
    [ "protocol.h", "protocol_8h.html", "protocol_8h" ],
    [ "sendEmail_new.cpp", "send_email__new_8cpp.html", null ],
    [ "server_interface.cpp", "server__interface_8cpp.html", null ],
    [ "server_interface.h", "server__interface_8h.html", "server__interface_8h" ],
    [ "server_logic.cpp", "server__logic_8cpp.html", null ],
    [ "server_logic.h", "server__logic_8h.html", "server__logic_8h" ],
    [ "servercore.cpp", "servercore_8cpp.html", null ],
    [ "servercore.h", "servercore_8h.html", "servercore_8h" ],
    [ "smtpclient.cpp", "smtpclient_8cpp.html", "smtpclient_8cpp" ],
    [ "smtpclient.h", "smtpclient_8h.html", "smtpclient_8h" ],
    [ "smtpclient_mailru.cpp", "smtpclient__mailru_8cpp.html", "smtpclient__mailru_8cpp" ],
    [ "smtpclient_mailru.h", "smtpclient__mailru_8h.html", "smtpclient__mailru_8h" ]
];